"""add quant metadata to model presets

Revision ID: 15a40d42352b
Revises: e4e77f9a615e
Create Date: 2026-03-25 01:21:53.074874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a40d42352b'
down_revision: Union[str, Sequence[str], None] = 'e4e77f9a615e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_presets', sa.Column('quantization', sa.String(length=50), nullable=True))
    op.add_column('model_presets', sa.Column('model_format', sa.String(length=50), nullable=True))
    op.add_column('model_presets', sa.Column('model_source', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_presets', 'model_source')
    op.drop_column('model_presets', 'model_format')
    op.drop_column('model_presets', 'quantization')
    # ### end Alembic commands ###
