"""add presentation_mapping to judgments

Revision ID: 33284c6a6797
Revises: f74fa45582d1
Create Date: 2026-02-19 01:49:05.307257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33284c6a6797'
down_revision: Union[str, Sequence[str], None] = 'f74fa45582d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judgments', sa.Column('presentation_mapping', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('judgments', 'presentation_mapping')
    # ### end Alembic commands ###
