"""no-op placeholder (originally rewrote pipeline suite descriptions)

Revision ID: a7b2e9f4c1d3
Revises: d5c6e7f8a9b0
Create Date: 2026-04-19 00:00:00.000000

History:
    This migration originally bulk-rewrote every ``prompt_suites`` row whose
    description started with ``Topic:`` or ``Generated by pipeline:`` to a
    metadata-derived "friendly" summary. That was destructive — users had
    hand-edited those descriptions (often keeping the ``Topic:`` prefix),
    and the rewrite silently clobbered their edits with a much longer
    rendering that embedded the entire ``generation_metadata.topic`` blob.

    Affected rows on the production DB were restored from the
    ``bellmark_20260418_224659.db`` backup. This file remains as a no-op so
    ``alembic_version`` stays consistent across machines that already applied
    the destructive upgrade.

    The current correct approach: the frontend simply trusts ``suite.description``
    as the source of truth (``getSuiteCardDescription`` in Suites.tsx). New
    suites get a friendly description at generation time via
    ``build_friendly_suite_description``. No bulk rewrite is performed on
    existing rows — if a legacy row still holds a technical description, the
    user can edit it themselves in the UI.
"""
from __future__ import annotations

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "a7b2e9f4c1d3"
down_revision: Union[str, Sequence[str], None] = "d5c6e7f8a9b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Intentionally no-op. See module docstring.
    pass


def downgrade() -> None:
    pass
